name: Run tests

on: [push, pull_request]

env:
  IMAGE_TAG: your-dockerhub-username/truffle-image

jobs:
  test:
    name: Docker build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run tests in Docker container
        run: |
          docker pull $IMAGE_TAG
          docker run --rm $IMAGE_TAG sh -c 'truffle test --network development'