name: Run tests

on: [push, pull_request]

env:
  IMAGE_TAG: world-token
  BASE_TOKEN_URI: https://example.com/token/

jobs:
  test:
    name: Docker build and test
    runs-on: ubuntu-latest
    services:
      ganache:
        image: trufflesuite/ganache-cli:latest
        options: --name ganache
        ports:
          - 8545:8545
    steps:

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t $IMAGE_TAG --target=truffle .

      - name: Run tests in Docker container
        run: docker run --rm --network=host -e BASE_TOKEN_URI=$BASE_TOKEN_URI $IMAGE_TAG sh -c 'truffle test'