name: Run tests

on: [push, pull_request]

env:
  IMAGE_TAG: world-token
  GANACHE_IMAGE: david9595/ganache-image:v1

jobs:
  test:
    name: Docker build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Pull Ganache Docker image
        run: docker pull $GANACHE_IMAGE

      - name: Build the Docker image
        run: docker build -t $IMAGE_TAG --target=truffle .

      - name: Run tests in Docker container
        run: |
          docker run --rm --network="host" $IMAGE_TAG sh -c 'truffle test --network ganache'