name: Run tests

on: [push, pull_request]

env:
  IMAGE_TAG: world-token
  GANACHE_IMAGE: david9595/ganache-image:v1

jobs:
  test:
    name: Docker build and test
    runs-on: ubuntu-latest
    services:
      ganache:
        image: $GANACHE_IMAGE
        ports:
          - 8545:8545
        options: --name ganache
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t $IMAGE_TAG --target=truffle .

      - name: Run tests in Docker container
        run: docker run --rm $IMAGE_TAG sh -c 'truffle test --network development'