name: Run tests

on: [push, pull_request]

env:
  IMAGE_TAG: world-token

jobs:
  test:
    name: Docker build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Start Ganache
        run: |
          docker run -d --name ganache david959/ganache-image:v1
          sleep 5 # Wait for Ganache to start

      - name: Build the Docker image
        run: docker build -t $IMAGE_TAG --target=truffle .

      - name: Run tests in Docker container
        run: |
          docker run --rm --network="host" $IMAGE_TAG sh -c 'truffle test --network ganache'

      - name: Stop Ganache
        run: docker stop ganache
