on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: run contract tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            yarn install truffle -g

      - name: Run tests
        run: yarn test