name: Run tests

on: [push, pull_request]

env:
  IMAGE_TAG: world-token

jobs:
  test:
    name: Docker build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t $IMAGE_TAG --target=truffle .

      - name: Run tests
        run: docker run $IMAGE_TAG sh -c 'yarn test'